version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: framework7-vue-cordova-boilerplate
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8080:8080"
    working_dir: /var/www
    volumes:
      - ./app:/var/www
